# Project
version=1.4
group=org.wishtoday.egar
java_version=17

# Common
minecraft_version=1.20.1
mod_name=enchanted_golden_apple_reborn
mod_author=Jared
mod_id=enchanted_golden_apple_reborn
license=CC0-1.0
credits=
minecraft_version_range=[1.20.1, 1.20.3)
description=
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false